### ISSUE TITLE
flyspell-correct-word-generic only shows possible corrections

### ISSUE THREAD

**Issue by thorstengrothe** [d12frosted/flyspell-correct#10]
as the header says flyspell-correct only shows possible corrections but not the options to 
to save unknown word to my dictionary, accept this spelling in current buffer or whole session. This is my setup

```
(use-package flyspell-correct
  :ensure t
  :after flyspell
  :bind (:map flyspell-mode-map
              ("C-<f8>" . flyspell-correct-word-generic))
  :config 
  (setq flyspell-correct-interface 'flyspell-correct-ivy)
  )
```

What I'm doing wrong?

Regards 
Thorsten

**Comment by d12frosted** [comment]
Which header?

```
;; When invoked, it will show the list of corrections suggested by Flyspell.
;; `ivy', `helm' and `popup' also allows to save unknown word to your
;; dictionary, accept this spelling in current buffer or whole session.
```

(from [here](https://github.com/d12frosted/flyspell-correct/blob/master/flyspell-correct.el#L24))

But previously it didn't allow to save words using `ivy` and `popup`, so probably you are just using out of date version - try to upgrade :)

**Comment by thorstengrothe** [comment]
I updated flyspell-correct, same result, look here:
http://www.zimagez.com/zimage/bildschirmfoto2016-05-2710-56-43.php
Regards
Thorsten

**Comment by d12frosted** [comment]
Ah. Now I understand your problem. `ivy` interface doesn't add `Save` actions to the list of completions, instead it uses common way to perform specific actions via `M-o`. When it asks for completion just press `M-o` and you'll see all available actions. Does it help you?

**Comment by thorstengrothe** [comment]
Yes thank you very much, didn't know that because helm-flyspell shows this per default, so I was a bit confused. Is there a way to do this per default without pressing M-O?

**Comment by d12frosted** [comment]
Yes, it's possible though it's not supported out of box. But since the purpose of `flyspell-correct` is allowing to use any custom interface, it's easy to implement one that inlines actions and use it:

```
(defun flyspell-correct-ivy-inline-actions (candidates word)
  "Run `ivy-read' for the given CANDIDATES given by flyspell for the WORD.
Return a selected word to use as a replacement or a tuple
of (command, word) to be used by flyspell-do-correct."
  (let* (result
         (action (lambda (x) (setq result x))))
    (ivy-read (format "Suggestions for \"%s\" in dictionary \"%s\": "
                      word (or ispell-local-dictionary
                               ispell-dictionary
                               "Default"))
              (append
               (mapcar (lambda (x) (cons x x)) candidates)
               (list (cons (format "Save \"%s\"" word) (cons 'save word))
                     (cons (format "Accept (session) \"%s\"" word) (cons 'session word))
                     (cons (format "Accept (buffer) \"%s\"" word) (cons 'buffer word))))
              :action action)
    result))

(setq flyspell-correct-interface 'flyspell-correct-ivy-inline-actions)
```

I hope it works :) But using actions is more idiomatic way of performing actions. I would recommend you to get used to them.

And also, just in case you missed that - `flyspell-correct` out of box also has the same interface as `helm-flyspell` named `flyspell-correct-helm`. You can use it as interface 😸

**Comment by thorstengrothe** [comment]
Thank you  very much for your help, now I have Save, Accept Session und Accept buffer, must look deeper in flyspell-correct-helm and configure flyspell to my needs!

**Comment by d12frosted** [comment]
To use `helm` interface just use

```
(setq flyspell-correct-interface 'flyspell-correct-helm)
```

Simple as that :)
