### ISSUE TITLE
Can this be a little more eager in searching backwards? 

### ISSUE THREAD

**Issue by sooheon** [d12frosted/flyspell-correct#13]
Modelling after the behaviour of flyspell-autocorrect-previous-word instead would be very nice:

`Auto correct the first misspelled word that occurs before point.
But don’t look beyond what’s visible on the screen.`

**Comment by d12frosted** [comment]
Hi, thanks for suggestion. I like the idea. 

I wonder what would be more helpful - two functions that behave differently or one function which behaviour depends on variable. Probably depends on feature implementation. 😸

**Comment by sooheon** [comment]
I think the seeking behaviour will be in every case equivalent or better. I also thought about making another issue for this, but I think it might depend on this implementation: point should stay exactly where it was invoked from. Currently, if it doesn't find a match, point will move forward a word or otherwise shift a bit.

**Comment by d12frosted** [comment]
> I think the seeking behaviour will be in every case equivalent or better

Probably you're right.

> I also thought about making another issue for this, but I think it might
depend on this implementation: point should stay exactly where it was
invoked from. Currently, if it doesn't find a match, point will move
forward a word or otherwise shift a bit.

Wow, didn't notice it. Nice catch! Please, open new issue for that :D

**Comment by d12frosted** [comment]
`flyspell-correct-previous-word-generic` is out in master. It reuses `flyspell-correct-word-generic`. It's mostly stolen code from `flyspell.el`. 😸
