### ISSUE TITLE
Describe ivy interface minibuffer commands

### ISSUE THREAD

**Issue by unbildung** [d12frosted/flyspell-correct#23]
Thanks for the package!

As I just started using Ivy, I am not very familiar with it, and I was having trouble figuring out how to switch from the list of dictionary candidates to the option menu to save, accept, etc. I looked at the Ivy [manual](http://oremacs.com/swiper/#key-bindings-for-navigation) and found the mini buffer command `M-o` or `ivy-dispatching-done`, which is what I needed. Perhaps you should note this in the documentation since, unlike the Helm and Popup interfaces, the Ivy interface hides the options menu.

**Comment by d12frosted** [comment]
Glad you like it. 

Yeah, you are not the only one confused by this. For example, #10. So yeah, it's a good idea to add some notes about using `ivy` interface. Will update readme soon.

Thanks for suggestion!
