### ISSUE TITLE
Scrolling in flyspell-correct-popup

### ISSUE THREAD

**Issue by sondr3** [d12frosted/flyspell-correct#24]
I was wondering if it was possible to make `flyspell-correct-popup` be able to scroll with `jk` instead of up/down arrow keys because I use Evil and would rather use them than the arrow keys.

**Comment by d12frosted** [comment]
Hey,

This problem should be addressed in configurations of interface you are using as it really out of scope of this package.

**Comment by sondr3** [comment]
Oh yeah, I was just wondering if you knew how I'd do it. But I figured it out on my own regardless, thanks though 😃

**Comment by d12frosted** [comment]
Sorry, but I don't use `evil`, so can't help you with setting up `jk` in `popup.el`. But the functions you need to setup are `popup-next` and `popup-previous`.

**Comment by sondr3** [comment]
Yep, got it to work with scrolling but can't get it to close with "q", oh well, small victories 😂
