### ISSUE TITLE
Add flyspell-correct-next-word-generic

### ISSUE THREAD

**Issue by mattiasb** [d12frosted/flyspell-correct#26]
I would want a similar function to `flyspell-correct-previous-word-generic` that searches forward instead of backwards and `flyspell-correct-next-word-generic` sounds like a good name. :)

Not sure if I have time/energy to add this myself anytime soon, but logging it here.

**Comment by d12frosted** [comment]
I like the idea. Must be simple to implement. I'll look into it very soon.

P. S. thanks for feature request 😸

**Comment by d12frosted** [comment]
Hey, I've implemented it. Should be on MELPA very soon. Let me know if it doesn't work for you.

**Comment by mattiasb** [comment]
Woop!

**Comment by mattiasb** [comment]
Works like a charm, thanks a lot!

**Comment by d12frosted** [comment]
Great to hear!
