### ISSUE TITLE
Ivy actions not available?

### ISSUE THREAD

**Issue by kolektiv** [d12frosted/flyspell-correct#28]
Reading the documents, it seems like the Ivy implementation uses the Ivy actions system, and mentions pressing `M-o` (when the minibuffer is offering a list of suggested words I assume). When I do this though it just accepts the selected word - so actually calls the default action, `correct`.

Am I doing something wrong or misunderstanding? How should access to save, etc. work? Sorry if this is a silly mistake on my part!

**Comment by kolektiv** [comment]
My apologies - it was my mistake! I was loading this using the use-package macro, but not via :demand - so it wasn't correctly adding the hook. My error entirely - thank you for an excellent useful tool!

**Comment by d12frosted** [comment]
Hey, glad to hear that it works 😸

**Comment by andschwa** [comment]
@kolektiv I just ran into this too... I feel like it should work out-of-the-box when using:

```
(use-package flyspell-correct-ivy
  :bind (:map flyspell-mode-map
              ([remap ispell-word] . flyspell-correct-wrapper)))
```

But I don't know enough about Emacs package conventions / auto-loading to set this up correctly.
