### ISSUE TITLE
underline marking of misspelled word remains after correction

### ISSUE THREAD

**Issue by Boruch-Baum** [d12frosted/flyspell-correct#31]
Hi. I just installed the package with the popup interface, and after correcting a word, the word remains underlined. When performing a flyspell correction manually (ie. M-$), the underline is correctly removed. (emacs 25, debian)

**Comment by Boruch-Baum** [comment]
Never mind. My mistake. The underline was due to "flyspell duplicate" deciding that "too" was a duplicate of "topi"

**Comment by d12frosted** [comment]
Hey @Boruch-Baum,

That happens 😸 Glad you are using `flyspell-correct` 😸
