### ISSUE TITLE
Broken popup UI when opened near end of buffer

### ISSUE THREAD

**Issue by freetonik** [d12frosted/flyspell-correct#37]
Hi,

thanks for a great package!

I noticed a little problem with popup. 

<img width="1279" alt="screen shot 2018-09-15 at 15 05 59" src="https://user-images.githubusercontent.com/2665931/45586069-e816ab00-b8f8-11e8-9871-c3bd5fef8a33.png">

Steps to reproduce:
1. Move point the end of a buffer.
2. Invoke popup for word via `flyspell-correct-popup`

**Comment by d12frosted** [comment]
Hi @freetonik 

Thanks for the feedback 😸 

I've tried to reproduce it and it works. What version of Emacs do you use? And is it GUI or terminal?

And just to make things clear, let me share the steps I tried (in case I missed something).

1. Make a mistake somewhere in the buffer.
2. Move the point to the end of the buffer, but make sure that the misspelt word is visible.
3. Invoke `flyspell-correct-previous-word-generic`.

P. S. A side question - do you use ivy and helm at the same time?

**Comment by d12frosted** [comment]
@freetonik 

First of all, thank you for such a detailed report! Secondly, I am able to reproduce these issues and it seems to be related to popup itself. To be honest, I don't know what to do with them.

> I'm in the process of switching from Helm to Ivy, this is why I was trying both flyspell-correct-ivy and -popup. I think I'll uninstall Helm soon.

I see 😸 I was using Helm for some time, but then totally switched to Ivy. The only thing that might be confusing with Ivy and `flyspell-correct-ivy` is invoking special commands (like save).

**Comment by freetonik** [comment]
I've submitted an issue to popup itself, hopefully this report will help. But last commit to popup's master was in 2016...

**Comment by d12frosted** [comment]
@freetonik Cool, thanks for letting me know. I wonder if it's gonna be fixed 😸 From my understanding it's not an easy fix. But it would be great.

**Comment by freetonik** [comment]
Yeah, it's quite obscure and edge-case-y...

Btw, is there a way to quickly select a candidate in `flyspell-correct-ivy` without hydras or other add ons? Something similar to the built-in `ispell-word`

<img width="1148" alt="screen shot 2018-09-17 at 13 02 12" src="https://user-images.githubusercontent.com/2665931/45617094-f0e2ba80-ba79-11e8-9f4f-acd1d10a5189.png">

Or I guess this more of a question about ivy than flyspell-correct.

**Comment by d12frosted** [comment]
> Or I guess this more of a question about ivy than flyspell-correct.

You are correct. However, I can share how I achieve this - `ivy-avy` function. By default, it's bound to `C-'`[1]. 

  [1]: https://oremacs.com/swiper/#key-bindings-for-single-selection-action-then-exit-minibuffer

**Comment by freetonik** [comment]
Ooh, I keep forgetting about ivy-avy! Thanks!
