### ISSUE TITLE
Differences between our two versions

### ISSUE THREAD

**Issue by Boruch-Baum** [d12frosted/flyspell-correct#48]
After your cherry-pick and all your subsequent work, I finally now have decided to integrate, merge and compare our two versions, and I notice two functional differences that affect the "user experience". If the differences are intentional decisions, that's cool, but I thought to point them out in case they were oversights.

1) In your version, when a user completes or aborts a spell-correct 'session', you return POINT to where it was before beginning the spell-correct 'session'. My version stays put at abort / finish point. I find this desirable because when one is in the process of correcting errors, one may abort mid-way upon seeing that a context needs more editing work than the simple correction provided by fly spell-correct.

2) Your version doesn't implement `flyspell-direction`. This was a feature to allow the user to determine the default direction of error-checking, and to allow toggling of direction to be persistent. Among my recent splurge of minor commits is a redefinition of the variable to a `defcustom`, named
`flyspell-correct-forward-direction`. With this, among other things, if one interrupts a correction operation in the middle of a document, the continuing command will remember the recent direction.

ref: https://github.com/Boruch-Baum/flyspell-correct

**Comment by d12frosted** [comment]
Hey @Boruch-Baum,

I know I am very slow to respond. And at last, I've got time to go over your points 😸 

> In your version, when a user completes or aborts a spell-correct 'session', you return POINT to where it was before beginning the spell-correct 'session'.

It's a really interesting point. For me, it's the killer feature of `flyspell-correct` - I can fix the error and continue what I was doing. Maybe I should provide a configuration variable for this. So everyone can make it perfect 😸 

> Your version doesn't implement flyspell-direction

This is something I just missed. Thanks for pointing it out.

**Comment by d12frosted** [comment]
I have broken this issue into two: #80 and #81.
