### ISSUE TITLE
Wrong type argument in `flyspell-correct-move`

### ISSUE THREAD

**Issue by UndeadKernel** [d12frosted/flyspell-correct#50]
When a buffer is first created, the mark is `nil`.
If the function `flyspell-correct-move` is called under this conditions, the following error will be shown:
```lisp
Wrong type argument: number-or-marker-p, nil
```
This is due to [this source line](https://github.com/d12frosted/flyspell-correct/blob/master/flyspell-correct.el#L244). The `(mark)` function returns `nil` and the command errors out.

**Comment by d12frosted** [comment]
Fixed by https://github.com/d12frosted/flyspell-correct/pull/51
