### ISSUE TITLE
Highlight the word that is currently being corrected

### ISSUE THREAD

**Issue by fikovnik** [d12frosted/flyspell-correct#52]
First, thank you for this package! Perhaps it can be achieved by other means, but I was wondering if it would be possible to add a custom face that would highlight the word that is currently being corrected?

**Comment by d12frosted** [comment]
Hey Filip,

That's a great idea. Thank you for sharing it. I am in travel mode, and will implement it once I am back to route.

**Comment by hubisan** [comment]
Was thinking the same and noticed that `ispell-word` is doing this. So I copied what is need from `ispell-word` and added an advice before and after `flyspell-correct-at-point` to highlight and unhighlight the current spelling error. Seems to work so far. 

This would probably be trivial to add as a feature. Don't have the time to make a pull request unfortunately.

```emacs-lisp
(defvar my-feat-spell-check/highlight-spelling-window nil
  "Window which has highlighted spellings.")

(defun my-feat-spell-check/flyspell-overlay-start-and-end ()
  "Return `cons' with start and end of `flyspell' overlay at point.
Returns nil if no overlay is found."
  (let ((ovs (overlays-at (point)))
        ov)
    (while (and (not ov) ovs)
      (let ((current (pop ovs)))
        (when (flyspell-overlay-p current)
          (setq ov current))))
    (when ov
      (let ((ov-start (overlay-start ov))
            (ov-end (overlay-end ov)))
        (cons ov-start ov-end)))))

(defun my-feat-spell-check/highlight-spelling-error ()
  "Highlight the spelling error at point."
  (setq my-feat-spell-check/highlight-spelling-window (selected-window))
  (when-let ((ov (my-feat-spell-check/flyspell-overlay-start-and-end))
             (ov-start (car ov))
             (ov-end (cdr ov)))
    (ispell-highlight-spelling-error ov-start ov-end t)))

(defun my-feat-spell-check/unhighlight-spelling-error ()
  "Highlight the spelling error at point."
  (save-window-excursion
    (select-window my-feat-spell-check/highlight-spelling-window)
    (ispell-highlight-spelling-error nil nil)))

(advice-add 'flyspell-correct-at-point :before #'my-feat-spell-check/highlight-spelling-error)
(advice-add 'flyspell-correct-at-point :after  #'my-feat-spell-check/unhighlight-spelling-error)
```

**Comment by d12frosted** [comment]
Wow, thank you for sharing the code. Will take a look on my weekends.

**Comment by d12frosted** [comment]
I tried it, but it seems it doesn't play nicely with overlays from `flyspell`.

**Comment by hubisan** [comment]
Works here. What you mean by not playing nicely so I can test it in my setup?

Forgot to mention, had to set an ispell variable (had to reload emacs after).:
```emacs-lisp
(setq ispell-highlight-face 'isearch)
;; defcustom ispell-highlight-face (if ispell-lazy-highlight 'isearch 'highlight)
```

Before correct:
![image](https://user-images.githubusercontent.com/4160043/72528100-8e1a5280-386a-11ea-9248-f08ff51c2204.png)


While correcting (avy-menu interface):
![image](https://user-images.githubusercontent.com/4160043/72528010-5d3a1d80-386a-11ea-8ee3-e060451f6fde.png)

Afterwards:
![image](https://user-images.githubusercontent.com/4160043/72528137-a68a6d00-386a-11ea-94a8-30bb1fc8f784.png)

**Comment by d12frosted** [comment]
Ok, there is something funky with my faces, that's why I didn't see the difference. Thanks for pointing out the value of `ispell-highlight-face`.

**Comment by d12frosted** [comment]
@hubisan I've created a PR based on your code. Would be grateful for your review ;)

**Comment by d12frosted** [comment]
@fikovnik, @gusbrs, @hubisan the feature is now available on master. Give some time for MELPA to build it :) 

P. S. Don't have any plans for stable MELPA. So let me know if you really-really need it there.

**Comment by gusbrs** [comment]
I'm trying it out here already, and it looks very nice indeed.

Thank you very much @d12frosted and @hubisan !
