### ISSUE TITLE
`flyspell-correct-avy-menu` unavailable

### ISSUE THREAD

**Issue by apc** [d12frosted/flyspell-correct#53]
I may be missing something but I cannot find `flyspell-correct-avy-menu` anywhere. I've tried browsing the package list, searching on MELPA, and doing a simple Google search (only a handful of hits for `"flyspell-correct-avy-menu"`. Of course, trying `use-package flyspell-avy-menu` tells me that the package cannot be found.

**Comment by d12frosted** [comment]
Hey @apc 

Right, I never published `avy` on the MELPA. If you want to use it now, you have to install it from the repository. You can use [straight.el](https://github.com/raxod502/straight.el) for this. 

```emacs-lisp
(use-package flyspell-correct-avy-menu
  :straight (flyspell-correct-avy-menu
             :type git
             :host github
             :repo "d12frosted/flyspell-correct"
             :files ("flyspell-correct-avy-menu.el"))
)
```

Didn't try this exact code, but should work if you configure `straight` to be used by `use-package`.

**Comment by d12frosted** [comment]
Please see https://github.com/melpa/melpa/pull/6580

**Comment by apc** [comment]
Thanks!

**Comment by d12frosted** [comment]
Should be available on MELPA soon.
