### ISSUE TITLE
`use-package` defer setup

### ISSUE THREAD

**Issue by Jesse-Millwood** [d12frosted/flyspell-correct#54]
If I am using `always-defer` with use-package is there anything extra I have to do so that the correct interface function is called? 

I am using
```
(use-package flyspell-correct-ivy
  :demand
  :bind ("C-M-;" . flyspell-correct-wrapper)
  :init
  (setq flyspell-correct-interface #'flyspell-correct-ivy))
```

and I get 
```
Error (use-package): Cannot load flyspell-correct-ivy
```

When trying to use flyspell ivy

Thanks for any pointers

**Comment by d12frosted** [comment]
Interesting. I am also using `always-defer` set to `t`. And my configuration is simple enough:

```
(use-package flyspell-correct-ivy
  :general
  (+leader-def
    "[s" '(flyspell-correct-wrapper :which-key "Spelling correction"))
  :init
  (setq flyspell-correct-interface #'flyspell-correct-ivy))
```

And when I call the `flyspell-correct-wrapper` I get the right function. I tried even without `general` to make sure it doesn't make any magic loading:

```
(use-package flyspell-correct-ivy
  :init
  (setq flyspell-correct-interface #'flyspell-correct-ivy))
```

`M-x flyspell-correct-wrapper` invokes `ivy` interface.

**Comment by Jesse-Millwood** [comment]
Thanks @d12frosted, do you have anything else special with either flyspell correct or ivy?

**Comment by d12frosted** [comment]
Well, sure I have some configurations for [ivy](https://gitlab.com/d12frosted/environment/blob/master/emacs/lisp/init-ivy.el) and [flyspell](https://gitlab.com/d12frosted/environment/blob/master/emacs/lisp/init-spellcheck.el). But not sure if it affects the loading.

P. S. I have set `defer t` everywhere - it's just a bad habit :)

**Comment by d12frosted** [comment]
@Jesse-Millwood any luck with deferring this package?

**Comment by Jesse-Millwood** [comment]
@d12frosted I haven't had any luck but I have been having similar issues with a couple other packages. FWIW, this is my init file: https://github.com/Jesse-Millwood/dots/blob/master/dot_emacs.d/init.el

**Comment by d12frosted** [comment]
@Jesse-Millwood I am little bit confused. As far as I understand you want to fix the issue with loading packages (as example, `flyspell-correct-ivy` is not properly loaded), but not to lazily load packages, right? And you try to do it by putting `:demand` on problematic packages, and you have global configuration with `:ensure t` and `:always-defer t`. 

Could you please try the following:

1. Start Emacs as usual.
2. Check that `flyspell-correct-ivy` is not loaded (e.g. just call `flyspell-correct-wrapper` as you normally do in the buffer with misspelled words).
3. Evaluate `(require 'flyspell-correct-ivy)` (can be done using `M-: (require 'flyspell-correct-ivy) <ret>`). 
4. Call `flyspell-correct-wrapper` again.

**Comment by Jesse-Millwood** [comment]
@d12frosted It seems that adding `:ensure t` worked! I did not have always ensure enabled globally. I guess I thought that only did things related to installation. I added the ensure enabled globally now, maybe it'll fix some other issues I've had. Thanks!

**Comment by d12frosted** [comment]
@Jesse-Millwood cool, glad that you sorted this out! happy hacking!
