### ISSUE TITLE
flyspell-correct-wrapper does nothing

### ISSUE THREAD

**Issue by WorldsEndless** [d12frosted/flyspell-correct#59]
Version: GNU Emacs 26.3 (build 1, x86_64-suse-linux-gnu, GTK+ Version 3.24.12)

Error: attempting `flyspell-correct-wrapper` does nothing at all

Steps to reproduce:
0. use-package the two things below, I think according to the readme instructions
1. insert text with mistypes into a buffer
2. execute `flyspell-buffer` to cause errors to be highlighted
3. Execute `flyspell-correct-wrapper`. Nothing happens and there is no message. 

If I instead execute flyspell-correct-next, things work as expected for a single correction; but I cannot try to use "rapid mode"

emacs init setup:

```
	(use-package flyspell-correct
	  :ensure t
	  :bind
	  :config
	  (define-key flyspell-mode-map (kbd "C-;") #'flyspell-correct-wrapper))

	(use-package flyspell-correct-helm
	  :ensure t        
	  :init
	  (setq flyspell-correct-interface #'flyspell-correct-helm))
```

**Comment by d12frosted** [comment]
Hey @WorldsEndless 

I have several questions to you :) 

1. Are you using `always-defer` option of `use-package`? If yes, then you should put keybinding configurations to the `:init` section (and in general it makes sense to do so).
2. In any case, do you see `flyspell-correct-wrapper` in the `flyspell-mode-map`?
3. Why are you using `:bind` without any arguments? It seems that you initially wanted to use [keybinding from use-package](https://github.com/jwiegley/use-package/#key-binding) but then switched to manual binding.

**Comment by WorldsEndless** [comment]
Thanks for the response.

1. always-defer is not on.

2. I used `C-h m` to look at mode specifications and I see flyspell, but there is no mention of correct-wrapper.

3. Yes, that was a mistype. I have removed that line, but there is no effect. In general I was unsure which commands I should put in one use-package and which in the other.

Still no response when I try calling flyspell-correct-wrapper, though.

**Comment by d12frosted** [comment]
1. Did you try moving the key binding to `:init` section? E.g. in this case chaning `:config` to `:init`?
2. Let's check the value of `flyspell-mode-map` by using `C-h v flyspell-mode-map <ret>`. Can you please share the output here?
3. Good 😸

**Comment by WorldsEndless** [comment]
Ah! I found it! I turns out the wrapper function is going in reverse to what I expected; in my workflows, I usually have point BEFORE my errors, but it seems that this function expects point to be after the errors unless you use a bunch of C-u before hand. I can adjust my workflow, though; the rapid mode is nice. Only I can't C-g out of it... but that's another issue.

**Comment by d12frosted** [comment]
@WorldsEndless haha, nice. Even didn't think about it. Well, I was thinking about introducing variables that control default behavior. And maybe allow to search in both directions.
