### ISSUE TITLE
flyspell-correct-ivy

### ISSUE THREAD

**Issue by atanasj** [d12frosted/flyspell-correct#65]
Hi,

The popup options with save to dictionary etc., have stopped working. Not sure why, I cannot get an error report out of it. However, when I press `M-o`, I get the text `Suggestions for … in dictionary "Default":`, but cannot see the options. Although, pressing one of the predefined options e.g., `M-o b` allows me to accept the word in buffer, but I just cannot see the options.

Here is  my config: 

```emacs-lisp
  (use-package flyspell-correct-ivy
    :bind ("C-M-;" . flyspell-correct-wrapper)
    :init
    (setq flyspell-correct-interface #'flyspell-correct-ivy))
```

Anyway I can fix this? I'm on `emacs 28.0.50` on `MacOS`. 

Cheers.

**Comment by d12frosted** [comment]
Wow, this is interesting. I could not reproduce until I've upgraded all my packages.

Here is what I get when I invoke `flyspell-correct-wrapper`.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/6507913/73843008-69d8e280-4826-11ea-845d-f06a05d0f247.png">

And here is what I get when I press `M-o` in that buffer.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/6507913/73843020-6fcec380-4826-11ea-8931-17e48be56992.png">

Are you talking about the second case?

**Comment by d12frosted** [comment]
Btw, actually `M-o` stopped to work in many other cases. For example, `counsel-find-file` also doesn't have any options in `M-o`. Looks like an upstream bug.

**Comment by atanasj** [comment]
Yes @d12frosted, I'm getting the same behaviour. I suppose we wait?

**Comment by d12frosted** [comment]
Can't reproduce on Emacs 26.3.

**Comment by atanasj** [comment]
Must be a but on Emacs 28.0.50…

**Comment by atanasj** [comment]
@d12frosted, do you think this is a but that will get corrected for use with the `--HEAD` version of Emacs?

**Comment by d12frosted** [comment]
I am not sure. I hadn't a chance to properly debug it and to understand the reason of breakage. I've opened an issue in swiper repo. And also checked the Emacs devel/bug mailing lists, but didn't find anything useful. Though I haven't spent much time on this.

**Comment by atanasj** [comment]
No worries. It would be great to get it working again… However, I get that 28.0.50 is the dev version and could change.

**Comment by d12frosted** [comment]
@atanasj workaround can be found here: https://github.com/abo-abo/swiper/issues/2444

**Comment by atanasj** [comment]
Thanks for that, I just installed `ivy-hydra`, and that seems to do the trick too. It's another dependency, but working none the less: 

![image](https://user-images.githubusercontent.com/27214625/74385072-cea7c480-4e46-11ea-8446-316d4c2578ec.png)

**Comment by d12frosted** [comment]
Fixed upstream.
