### ISSUE TITLE
"save <CHANGE>" is broken

### ISSUE THREAD

**Issue by WorldsEndless** [d12frosted/flyspell-correct#66]
Using -helm. When a mistype is found and I type-in what it should be, I can then click "Save" my correction, but it doesn't actually correct my word. Example
```
;; Buffer Text: cook3s

(M-x flyspell-correct-buffer) ;; word "cook3s" is underlined as incorrect
(flyspell-correct-wrapper) ;; goes to "cook3s" and offers options
;; Type "cookies" and  press enter on "Save cookies"
;; Message: Personal dictionary saved.
;; The word cook3s is no longer underlined as incorrect, but is not changed to cookies as expected
```

**Comment by d12frosted** [comment]
Save action is used to add a 'misspelled' word to a dictionary.

**Comment by WorldsEndless** [comment]
In the past (before using flyspell-correct) it served to save a hand-written correction to the buffer. In any case, how do I type my correction in manually if it doesn't appear on the suggestion list?

**Comment by d12frosted** [comment]
Ok, now I get your question. I never use helm, so I wasn't aware, that there is a bug.

**Comment by d12frosted** [comment]
I will fix it soon. I just need to get to my computer.

**Comment by d12frosted** [comment]
The fix is in master. Please verify and let me know how it goes 😸

**Comment by WorldsEndless** [comment]
Beautiful! I can now hand-type correction in addition to selecting them from the list. Thanks!

**Comment by d12frosted** [comment]
Cool. I am glad that it works. Thank you for reporting.
