### ISSUE TITLE
Can't use flyspell-correct-word

### ISSUE THREAD

**Issue by manuel-uberti** [d12frosted/flyspell-correct#7]
Hi,

first of all thanks for the package and for the chance to use Ivy with Flyspell. 

I'm using latest `flyspell-correct` from MELPA. Whenever I issue `flyspell-correct-word` on mispelled a word, this is the message that I get:
```
flyspell-correct-word must be bound to an event with parameters
```
I am using GNU Emacs 25.0.93.1 (x86_64-debian-linux-gnu, GTK+ Version 3.14.5) of 2016-05-06.

**Comment by d12frosted** [comment]
Ah. That's because the function called `flyspell-correct-word-generic` and not `flyspell-correct-word` :)

**Comment by manuel-uberti** [comment]
Oh yes, I'm an idiot. It works just fine. :)

**Comment by d12frosted** [comment]
Don't blame yourself :) I think it's also because I didn't use a better name.
