### ISSUE TITLE
flyspell-correct-ido on Melpa

### ISSUE THREAD

**Issue by robstewart57** [d12frosted/flyspell-correct#74]
The `flyspell-correct-ido` package is not on Melpa, but the packages for:

- avy-menu
- helm
- ivy
- popup

https://melpa.org/#/?q=flyspell-correct

Could the `flyspell-correct-ido` package also be uploaded to Melpa?

**Comment by d12frosted** [comment]
@robstewart57 pleased to see your interest in `ido` interface! The good news - it's already part of `flyspell-correct` package. You can see the recipe in [MELPA repository][1]. So you can just install this package and use `ido` interface.

  [1]: https://github.com/melpa/melpa/blob/master/recipes/flyspell-correct

**Comment by robstewart57** [comment]
Ah, I hadn't realised. Thanks very much for this package, it's a lot of fun to use!
