### ISSUE TITLE
Can't 'accept' correction with keyboard (flyspell-correct-popup)

### ISSUE THREAD

**Issue by thomasheartman** [d12frosted/flyspell-correct#90]
I have an issue where sometimes (fairly often), 'accepting' an entry from the popup menu doesn't work when using the keyboard. That is, when using one of the `flyspell-correct-` functions, the popup opens with the expected options, but nothing happens when I press `<return>`. Navigation and cancellation works just fine, and selecting an option with the mouse also seems to work, just not with the keyboard. 

It seems to happen in both org and markdown files, and it happens regularly, but not consistently. It does not seem to be related to the contents of the document, as I can copy the contents from the buffer where it doesn't work and paste them into the scratch buffer (or some other buffer where selecting options works) and have things work as expected.

From what I gather, the popup-package is based on [this flyspell-popup package](https://github.com/xuchunyang/flyspell-popup), so that might be the right place to report this, but I thought I'd check in here first.

Thinking it might be based on the above package, I also tried explicitly adding `<return>` as `popup-select` in the `popup-menu-map`, but that didn't seem to change anything.

Do you know what this is about? I tried looking for similar issues, but couldn't find any.

Current commit of the package: `d19a090b978a249fc8f6d8b14309a5705a6bb483`

I'd be happy to provide you with any more information you might need. Just let me know! Thank you :pray:

Oh, and when this package works as expected, it really is superb, so I'd love to figure out what's going on here.

**Comment by d12frosted** [comment]
Hey,

Curious issue. I am returning from vacation and will test it by myself once I have a solid I/C. So far I have the following questions and ideas.

1. Could you please try to reproduce the issue in `emacs -Q` mode? It might be that some of your configurations are interfering. Especially for org-mode/popup.
2. What Emacs version are you using?
3. Could you please run the following code in `org-mode` buffer and check if `<return>` works as expected? (e.g. `M-: <code> <return>`).

```emacs-lisp
(popup-menu*
 (list
  (popup-make-item "one" :value 1)
  (popup-make-item "two" :value 2)))
```

> From what I gather, the popup-package is based on this flyspell-popup package, so that might be the right place to report this, but I thought I'd check in here first.

`flyspell-correct-popup` is not based on `flyspell-popup`, there are multiple divergences between these two packages. But I wound not be surprised if both are affected.

> I'd be happy to provide you with any more information you might need. Just let me know! Thank you 🙏

Let's find out what's causing this nasty issue :)

> Oh, and when this package works as expected, it really is superb, so I'd love to figure out what's going on here.

Really happy to hear :)

**Comment by d12frosted** [comment]
I juse checked your [dotfiles][1] and have few more options to check. I see that you do some magic around `<return>`, for example:

1. [multiple-cursors][2];
2. You bind `<return>` to `my-evil-insert-line-below`.

Could you please disable these configs to validate if it resolves the issue?

  [1]: https://github.com/thomasheartman/dotfiles/blob/main/.emacs.d/config.org 
  [2]: https://github.com/thomasheartman/dotfiles/blob/main/.emacs.d/config.org#multiple-cursors

**Comment by thomasheartman** [comment]
Ooh, I think you're on to something there! I don't have the time right now to delve much deeper into it, but I think I found what's causing it:

It seems that if the popup opens while I'm in normal mode, then I can't accept the corrections, whereas if I'm in insert mode it *does* work. As such, you're probably right in that it's the `my-evil-insert-line-below` mapping that causes it.

I'm not entirely sure how Evil works, but from what I gather, it pretty much overrides all other active keymaps, doesn't it? That might explain why the bindings in `popup-menu-map` don't trigger correctly (at least if that is the correct minor mode). 

So yeah, this is most likely just a user error, and I'd be happy to close the issue (or for you to do it) unless you want to keep it open?

If you have any ideas on how to get around this I'd be very interested in hearing them, but if you don't, I'll go digging on my own.

Thanks!

**Comment by d12frosted** [comment]
> I'm not entirely sure how Evil works, but from what I gather, it pretty much overrides all other active keymaps, doesn't it?

I am not using Evil, so can's say for sure 😺 . I guess so. And I think that either your configuration or evil in general (this is something you can easily check by commenting your override of `<return>`) is overriding `popup-menu-keymap` or interfiring `popup-menu-read-key-sequence` in some way.

> As such, you're probably right in that it's the my-evil-insert-line-below mapping that causes it.

You can check what `<return>` is bound to in `normal` mode by default in evil, might be helpful if by default evil works fine with popup.

**Comment by thomasheartman** [comment]
I think you're spot on with what you're saying! If I don't map `<return>` in normal mode, then it seems that Evil doesn't map it at all, and the selection works as expected. Luckily, Evil provides a variable called `evil-overriding-maps` which is a list of keymaps that should override Evil maps. Allowing `popup-menu-keymap` to override evil is part of fixing the issue:

```emacs-lisp
(add-to-list 'evil-overriding-maps '(popup-menu-keymap . nil))
```

However, even with that, I still had to add an explicit binding of `<return>` to `popup-menu-keymap` for it to work. It seems that in the original definition it doesn't bind `<return>`, but instead binds `\r`. Am I reading that definition right and, if so, is there a reason for that?

Thanks for all the help debugging this, by the way :smile:

**Comment by d12frosted** [comment]
> Am I reading that definition right and, if so, is there a reason for that?

This is what I saw as well. And AFAIK these are equivalent (and I am sure there are many more options including `C-m` variants, 13 - code of `\r` char, `^M` etc):

```emacs-lisp
(global-set-key "\r" #'func)
(global-set-key [return] #'func)
(global-set-key (kbd "<return>") #'func)
(global-set-key (kbd "RET") #'func)
```

Emacs has adopted multiple ways to represent non-printable characters. Some come from C langauge (e.g. `\r`), some come from... 🤔 I don't know where 😸 I bet the answer for the most important question would be - for historical reasons 😸 

> Thanks for all the help debugging this, by the way 😄

You are welcome 😸 Happy that I could help! Thanks for sharing the solution.

P. S. Closing this issue as it seems that you resolved the problem.

**Comment by d12frosted** [comment]
@thomasheartman Look what I found - http://ergoemacs.org/emacs/keystroke_rep.html . Explains the situation a little bit.

**Comment by thomasheartman** [comment]
Nice; thanks! That still doesn't explain why the explicit return mapping would be necessary though (considering that `\r` and `<return>` should be the same character).  I tried removing the `<return>` mapping in favor of a `\r` mapping and it didn't work, but using `<return>` works. Could it be that my evil mapping takes precedence in this case? :thinking:
